### ISSUE TITLE
Project's website returns 404

### ISSUE THREAD

**Issue by ynezz** [lunarmodules/lualogging#5]
I'm not able to reach https://keplerproject.github.io/lualogging due to 404 error.

**Comment by alerque** [comment]
It looks like the new URL is going to be https://lunarmodules.github.io/lualogging. This org is new so some URLs both inside and out of the project are going to need updating. The sidebar link is one obvious place to start, the README next.

**Comment by Tieske** [comment]
@ynezz we just started moving some repos into a new org, we'll update those links over the next couple of days. For now you can use the link @alerque provided.

**Comment by ynezz** [comment]
So #7 should help fixing that, the last one is probably the project's sidebar.

![image](https://user-images.githubusercontent.com/43848/92459213-af97c800-f1c6-11ea-8bcb-b23b5a250f67.png)
